### ISSUE TITLE
Contracts not being generated in random planets

### ISSUE THREAD

**Issue by Not-Erik** [BlueWinds/WarTechIIC#6]
Hello! It's me again.

Project is mostly going fine, but for some reason contracts are not generated in random planes. When we turn off the mod, it generates contracts normally. Following errors should be connected with the issue:

04:11:51.8554479 Unity [ERROR] Mid-interpolation null value on object MagistracyOfCanopus with expr 'FactionDef.heraldryDefId')
04:14:47.6144728 SimGameState [ERROR] There are no valid employers or targets for the system of Balawat
04:14:47.6144779 SimGameState [ERROR] System Employers:
04:14:47.6144793 SimGameState [ERROR] 	Locals
04:14:47.6144824 SimGameState [ERROR] 	Locals Enemies:
04:14:47.6144834 SimGameState [ERROR] 		AuriganPirates
04:14:47.6144838 SimGameState [ERROR] 		Davion
04:14:47.6144841 SimGameState [ERROR] 		Kurita
04:14:47.6144846 SimGameState [ERROR] 		Liao
04:14:47.6144849 SimGameState [ERROR] 		Marik
04:14:47.6144853 SimGameState [ERROR] 		Steiner
04:14:47.6144857 SimGameState [ERROR] 		TaurianConcordat
04:14:47.6144861 SimGameState [ERROR] 		MagistracyOfCanopus
04:14:47.6144865 SimGameState [ERROR] 	MagistracyOfCanopus
04:14:47.6144871 SimGameState [ERROR] 	MagistracyOfCanopus Enemies:
04:14:47.6144876 SimGameState [ERROR] 		AuriganPirates
04:14:47.6144879 SimGameState [ERROR] 		AuriganDirectorate
04:14:47.6144882 SimGameState [ERROR] 		TaurianConcordat
04:14:47.6144885 SimGameState [ERROR] 		Liao
04:14:47.6144888 SimGameState [ERROR] 		Kurita
04:14:47.6144890 SimGameState [ERROR] System Targets:
04:14:47.6144892 SimGameState [ERROR] Ignored Employers:
04:14:47.6144894 SimGameState [ERROR] Ignored Targets:
04:14:47.6144900 SimGameState [ERROR] 	AuriganDirectorate
04:14:47.6144904 SimGameState [ERROR] 	NewFlakJackals
04:14:47.6144908 SimGameState [ERROR] 	ToppletiffHoldings
04:14:47.6144914 SimGameState [ERROR] 	santandersKillers
04:14:47.6144917 SimGameState [ERROR] 	wilsonsHussars
04:14:47.6144920 SimGameState [ERROR] 	HouseCunningham
04:14:47.6144923 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144925 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144928 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144931 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144933 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144936 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144939 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144941 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144944 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144947 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144950 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144953 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144956 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144958 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144961 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144963 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144966 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144978 SimGameState [ERROR] 	INVALID_UNSET
04:14:47.6144982 SimGameState [ERROR] 	barramedasBlackguards
04:14:47.6144984 SimGameState [ERROR] 	indriConsortium
04:14:47.6144987 SimGameState [ERROR] 	irukjandiCompany
04:14:47.6144990 SimGameState [ERROR] 	wagyuBarons
04:14:47.6144994 SimGameState [ERROR] 	agrarianCollective
04:14:47.6144999 SimGameState [ERROR] 	antianLanciarii
04:14:47.6145002 SimGameState [ERROR] 	durachi
04:14:47.6145006 SimGameState [ERROR] 	froness
04:14:47.6145009 SimGameState [ERROR] 	girin

**Comment by BlueWinds** [comment]
Sorry I didn't notice this; github notifications were broken on my end for a while. Going to close this as stale; if you're still having problems, go ahead and open a new issue and I won't ignore it this time!
